### ISSUE TITLE
Button "source" is broken

### ISSUE THREAD

**Issue by leo** [zeit/hyperterm-website#3]
I'm not sure if this is intentionally or related to [zeit/now](https://github.com/zeit/now), but the "source" link at the bottom opens a page with a 404 error: https://hyperterm.now.sh/_src

![linky 2x](https://cloud.githubusercontent.com/assets/6170607/16668044/a621951e-448f-11e6-9c05-90bdf8a80093.png)

**Comment by rauchg** [comment]
@leo let's revisit this and re-add the link once we have `now publish` and `now unpublish`

**Comment by leo** [comment]
k
